[package]
name = "jack-volume"
version = "0.1.0"
authors = ["Richard Dodd <richard.o.dodd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jack = { path = "../rust-jack" }
log = "0.4.6"
pretty_env_logger = "0.3.0"
structopt = "0.2.18"
crossbeam-channel = "0.3.8"
num = "0.2.0"
gtk = { version = "0.7.0", features = ["v3_16"] }
gio = { version = "0.7.0", features = ["v2_44"] }
gdk = "0.11.0"
nom-midi = "0.5.0"
nom = "5.0.0"
